---
- name: Teamspeak
  hosts: "cloud"
  vars:
    ts_version: 3.13.7
    mariadb_version: 11.4.9
    mariadb_hostname: mariadb-ts
    ts_db_dump_host_dir: /home/val/ts-db-dump
  vars_files:
    - secrets.yml
  tasks:
    # ansible-galaxy collection install containers.podman
    - name: Create container network "ts"
      containers.podman.podman_network:
        name: ts

    # ansible-galaxy collection install containers.podman
    - name: Run MariaDB container
      containers.podman.podman_container:
        name: "{{ mariadb_hostname }}"
        image: docker.io/library/mariadb:{{ mariadb_version }}
        detach: true
        hostname: "{{ mariadb_hostname }}"
        network:
          - ts
        pull: newer
        #force_restart: true # see https://github.com/containers/ansible-podman-collections/issues/816
        restart_policy: always
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "mariadb-ts:/var/lib/mysql"
          # - "{{ ts_db_dump_host_dir }}:/docker-entrypoint-initdb.d" # for initializing the database
        env:
          MARIADB_ROOT_PASSWORD: "{{ vault_ts_db_root_pw }}"
          MARIADB_DATABASE: teamspeak
          MARIADB_USER: teamspeak
          MARIADB_PASSWORD: "{{ vault_ts_db_user_pw }}"
        state: started

    # ansible-galaxy collection install containers.podman
    - name: Run TS container
      containers.podman.podman_container:
        name: teamspeak
        image: docker.io/library/teamspeak:{{ ts_version }}
        detach: true
        network:
          - ts
        ports:
          - 9987:9987/udp
          - 30033:30033/tcp
        #force_restart: true
        restart_policy: always
        volumes:
           - "/etc/localtime:/etc/localtime:ro"
           - "teamspeak:/var/ts3server"
        env:
          TS3SERVER_DB_PLUGIN: ts3db_mariadb
          TS3SERVER_DB_SQLCREATEPATH: create_mariadb
          TS3SERVER_DB_HOST: "{{ mariadb_hostname }}"
          TS3SERVER_DB_USER: teamspeak
          TS3SERVER_DB_PASSWORD: "{{ vault_ts_db_user_pw }}"
          TS3SERVER_DB_NAME: teamspeak
          TS3SERVER_DB_WAITUNTILREADY: "30"
          TS3SERVER_LICENSE: accept
        state: started
